### PR TITLE
reduce an if in function rotate(rotation)

### PR DESCRIPTION
**Pull request by gingerbeardman**
- feel free to not accept if this is not the type of optimisation you are looking for

### CODE REVIEW

**Comment by thacuber2a03** [comment]
I *think* I've already tried that before and it did not work?
I'd have to check if it does work before merging

**Comment by thacuber2a03** [comment]
that didn't work
[Grabación de pantalla desde 28-04-23 20:15:42.webm](https://user-images.githubusercontent.com/70547062/235272415-9cf82e7c-e49e-44e8-b73f-4e3545dcdda2.webm)
I tried removing the -1 at the end and it rotates fine again, but it breaks SRS more than it already is

**Comment by gingerbeardman** [comment]
Weird, when implemented it I printed existing logic results next to new logic results and they were identical.

**Comment by gingerbeardman** [comment]
D'OH!

My code recreated piece.rotation, not chosenRotation LOL.

Sorry about that!

**Comment by thacuber2a03** [comment]
a

**Pull request closed without merging**
