### PR TITLE
Feature/lock delay

### PR DESCRIPTION
**Pull request by mikedinicola**
Putting this in draft while I wait for some others to test it out!

Note: main wasn't merged into dev so when you review this you'll see the sash fixes as well. You could merge main into dev before reviewing this if it's confusing

### CODE REVIEW

**Comment by thacuber2a03** [comment]
I'll merge this *after* I commit the fixed SRS (which I don't want it to be a permanent fix tbh), since it might make merge conflicts

**Comment by thacuber2a03** [comment]
Still in draft?

**Comment by mikedinicola** [comment]
Yeah I have a minor graphical issue to sort out, might have time tonight, if not over the weekend

**Comment by mikedinicola** [comment]
Ready to go :)

**Comment by thacuber2a03** [comment]
less gooo

**Pull request merged**
