### PR TITLE
Add a new "big blocks" option

### PR DESCRIPTION
**Pull request by obra**
This PR updates how we position game metadata and adds a new feature that lets the user toggle brick size to 13x13 instead of 11x11.

@ThaCuber - please let me know if you'd like any changes.

### CODE REVIEW

**Comment by thacuber2a03** [comment]
Dang, you changed so many things! I'll try the new option tomorrow. For now I'll merge the PR to the- wait, why do you wanna move it to the main branch? I'd actually prefer it if you put it on the dev branch till I actually end up releasing update 1.5 (which might be tomorrow)(today considering I said this at 2am, don't ask why)

**Comment by obra** [comment]
It was supposed to be on dev. I'm so sorry. Let me fix that.

**Comment by thacuber2a03** [comment]
whoops there's merge conflicts now

**Comment by thacuber2a03** [comment]
and i think it's because you wrote it with the released version's code 😥

**Comment by obra** [comment]
Yeah, I screwed up by not git pulling correctly against dev after your last push. I worked against something past 1.4.1 but not the HEAD of dev. I'm rebasing now, but may not pull it off before I need to crash out tonight. But it's my bad and I'm reworking.

**Comment by obra** [comment]
Ok. Rebased on top of the "correct" dev branch.  Loving the new stuff you've done :)

**Comment by thacuber2a03** [comment]
epic, thanks

**Pull request merged**
