### PR TITLE
Added ability to rotate pieces via crank, fixed "shake" and "ghost" settings bug

### PR DESCRIPTION
**Pull request by tedbrakob**
Added ability to rotate pieces via crank
Added .vscode settings directory to gitignore

Note: Crank rotation is handled in `updateGame()` instead of an input handler like a/b rotation because there is no input handler equivalent to `playdate.getCrankTicks()`

### CODE REVIEW

**Comment by tedbrakob** [comment]
Found a bug on starting the game on a fresh install.  Will fix and remove draft status.

**Comment by tedbrakob** [comment]
bug fixed, ready for review

**Comment by thacuber2a03** [comment]
`handleCrankRotation` could very well be shortened and even inlined back in the main loop, but it's fine like that.
also, I never thought of skipping a rotation if the piece was an O piece, that's some performance boosts I guess

**Comment by thacuber2a03** [comment]
let me build it and release it as minor version real quick

**Comment by thacuber2a03** [comment]
nonononono nope, wait, I'll add something before that

**Comment by tedbrakob** [comment]
Copied the "O" rotation skip from what is already in place for a/b buttons.  Not sure how big of an improvement that makes, but I figured I would include it

**Pull request merged**
